# Generated by Django 3.2.5 on 2022-03-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='My_Users',
        ),
    ]
