# Generated by Django 3.2.5 on 2022-03-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_rename_myusers_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
